### ISSUE TITLE
Where could I get ALL_LABELS.txt

### ISSUE THREAD

**Issue by mingyangligithub** [bvanaken/ProtoPatient#1]
Hi authors,

I'm interested in your work and I'm trying to reproduce it. I have two questions about the files needed in the training,

1. Is the train.csv, val.csv and test.csv are the ones processed from CAML?
2. Where could I get ALL_LABELS.txt?

Many thanks!
Kind regards!

**Comment by bvanaken** [comment]
Hi Mingyang,

thanks for your interest in our work!

For our setup, we used the diagnosis prediction task from the clinical outcome prediction dataset introduced in the paper: [Clinical Outcome Prediction from Admission Notes using Self-Supervised Knowledge Integration](https://aclanthology.org/2021.eacl-main.75). It is produced from MIMIC-III files, so you will need to request access to the dataset on [Physionet](https://physionet.org/content/mimiciii/1.4/) first.

To get train.csv, val.csv and test.csv and the ALL_LABELS file, please check out this repository: https://github.com/bvanaken/clinical-outcome-prediction, with instructions on how to create the files. The correct task script to run here is **dia.py** (with _admission_only=True_). Then you will get train, val, test and a file called ALL_3_DIGIT_DIA_CODES.txt which is equivalent to the ALL_LABELS.txt file.

I hope that helps!
Best, Betty
